// UI strings: ko / en / ja / zh
const LANGS = ["ko", "en", "ja", "zh"];
const LANG_NAMES = { ko: "한국어", en: "English", ja: "日本語", zh: "中文" };
const STR = {
  ko: {
    home: "⌂ 홈", homeTitle: "여행 목록",
    mapStreet: "🗺 일반", mapSat: "🛰 위성", mapTerrain: "⛰ 지형", mapBld: "🏢 3D",
    tripsTitle: "여행 선택", localOpen: "📂 내 폴더 열기",
    noTrips: "📂 내 폴더 열기로 로컬 travel 폴더를 지정하세요 (사진은 브라우저에서만 읽고 업로드되지 않음)",
    play: "▶ 재생", pause: "⏸ 정지", first: "⏮ 처음", firstTitle: "첫 사진 위치로",
    normal: "정배속", manualBtn: "📍 위치지정", manualBtnTitle: "GPS 없는 구간 위치 직접 지정",
    heldChk: "추정 표시", follow: "따라가기",
    manualTitle: "📍 위치 직접 지정", mqPh: "예: 청주국제공항", search: "검색",
    searching: "검색 중...", noResult: "결과 없음", searchFail: "검색 실패(네트워크): ",
    placeFallback: "지정위치",
    scopeCurrent: "지금 보고 있는 사진 1장", scopeBefore: "첫 GPS 이전 사진 전부", scopeRange: "시간 범위 지정",
    photoUnit: "장",
    mnote: "지정한 위치가 새 앵커가 되어 앞뒤 사진이 규칙대로 재배치됨 · JPEG 원본 EXIF에도 기록 (쓰기 허용 폴더)",
    apply: "적용", rulesTitle: "지정 목록", export: "내보내기", import: "가져오기",
    del: "삭제", none: "없음", notArray: "배열 아님",
    scopeBeforeList: "첫 GPS 이전 전부", photoOne: "사진 1장: ",
    badgeGps: "GPS확정", badgeHeld: "같은장소", badgeManual: "직접지정",
    segStay: "🚶 체류", segWalk: "🚶 도보/체류", segTransit: "🚇 탈것", segPlane: "✈️ 비행기", segShip: "🚢 배",
    segManualFallback: "직접지정",
    day: "{n}일차", airport: "공항", stay: "숙소",
    interlude: "{n}일차 시작 — 기상 + 짐싸기",
    stats: "전체 {total} · GPS {gps} · 같은장소 {held} · 직접 {manual} · {start} ~ {end}",
    infoTime: "시간", infoMove: "이동", infoAt: "배치", infoFile: "파일",
    heic: "HEIC 미리보기 미지원", heicDl: "원본 다운로드",
    mapIs: "지도: {x}", mapFailOver: "지도 실패 → {x}로 전환", mapFailAll: "지도 로드 실패 (네트워크 확인 필요)",
    mapTileErr: "지도 타일 오류 — 네트워크 확인", styleFail: "지도 스타일 로드 실패 — 새로고침 해주세요",
    initFail: "초기화 실패: ",
    openFailRo: "폴더 열기 실패, 읽기 전용으로 시도: ", reading: "읽는 중 {a}/{b}...", readFail: "읽기 실패: ",
    gpsNoNeed: "GPS 확정 사진은 지정할 필요 없음", needRange: "시간 범위를 입력하세요",
    importFail: "가져오기 실패: ",
    wNoPiexif: "원본 기록 불가: piexif 로드 실패",
    wNoPerm: "원본 기록 불가: 쓰기 권한 없음(폴더를 다시 열어 허용) · {n}장 화면에만 적용",
    wNoJpeg: "원본 기록: JPEG 아님 {n}장 제외, 화면에만 적용",
    wProg: "원본 기록 중 {a}/{b}...",
    wDone: "원본 기록 완료: 성공 {ok}{fail} · GPS 앵커 승격",
    wDoneFail: ", 실패 {n}", wDoneSkip: ", 제외 {n}",
    minTitle: "접기/펼치기", localTag: "(내 폴더)", emptyTrip: "배치된 사진 없음 (촬영 시간 정보 필요)", compassTitle: "북쪽으로",
    heroTitle: "3D 여행 지도 — 사진으로 다시 걷는 여행",
    heroD1: "여행 사진 속 촬영 시간과 GPS를 읽어 3D 지구본 위에 시간순 여행 경로를 자동으로 그립니다.",
    heroD2: "GPS가 없는 사진은 같은 장소에 모아두고, 폴더를 지정하는 것만으로 경로·재생·일차별 이동이 완성됩니다.",
    heroD3: "사진은 브라우저에서만 읽고 어디에도 업로드되지 않습니다.",
    gpsOverwrite: "이미 GPS 값이 있는 사진 {n}장이 포함되어 있습니다. 진짜로 덮어씌우시겠습니까?",
    exifrFail: "exifr 로드 실패(네트워크 확인)", noPhotos: "사진/영상이 없음", wPiexif: "piexif 로드 실패", wVerify: "검증 실패",
  },
  en: {
    home: "⌂ Home", homeTitle: "Trip list",
    mapStreet: "🗺 Streets", mapSat: "🛰 Satellite", mapTerrain: "⛰ Terrain", mapBld: "🏢 3D",
    tripsTitle: "Select trip", localOpen: "📂 Open folder",
    noTrips: "📂 Open a local travel folder (photos stay in your browser, nothing is uploaded)",
    play: "▶ Play", pause: "⏸ Pause", first: "⏮ Start", firstTitle: "Go to first photo",
    normal: "1x", manualBtn: "📍 Set location", manualBtnTitle: "Manually set location for no-GPS section",
    heldChk: "Show estimates", follow: "Follow",
    manualTitle: "📍 Set location manually", mqPh: "e.g. Cheongju Airport", search: "Search",
    searching: "Searching...", noResult: "No results", searchFail: "Search failed (network): ",
    placeFallback: "Pinned place",
    scopeCurrent: "Current photo only", scopeBefore: "All photos before first GPS", scopeRange: "Time range",
    photoUnit: " photos",
    mnote: "The pinned place becomes a new anchor and nearby photos are re-placed · Also written to JPEG EXIF (writable folder)",
    apply: "Apply", rulesTitle: "Saved", export: "Export", import: "Import",
    del: "Delete", none: "None", notArray: "Not an array",
    scopeBeforeList: "Everything before first GPS", photoOne: "Photo: ",
    badgeGps: "GPS", badgeHeld: "Placed", badgeManual: "Manual",
    segStay: "🚶 Stay", segWalk: "🚶 Walk/stay", segTransit: "🚇 Transit", segPlane: "✈️ Flight", segShip: "🚢 Ferry",
    segManualFallback: "Manual",
    day: "Day {n}", airport: "Airport", stay: "Stay",
    interlude: "Day {n} start — wake up + pack",
    stats: "Total {total} · GPS {gps} · Placed {held} · Manual {manual} · {start} ~ {end}",
    infoTime: "Time", infoMove: "Move", infoAt: "At", infoFile: "File",
    heic: "HEIC preview unsupported", heicDl: "Download original",
    mapIs: "Map: {x}", mapFailOver: "Map failed → switched to {x}", mapFailAll: "Map load failed (check network)",
    mapTileErr: "Map tile error — check network", styleFail: "Map style load failed — please reload",
    initFail: "Init failed: ",
    openFailRo: "Folder open failed, trying read-only: ", reading: "Reading {a}/{b}...", readFail: "Read failed: ",
    gpsNoNeed: "GPS photos need no manual pin", needRange: "Enter a time range",
    importFail: "Import failed: ",
    wNoPiexif: "Cannot write originals: piexif failed to load",
    wNoPerm: "Cannot write originals: no write permission (reopen the folder) · {n} shown on screen only",
    wNoJpeg: "Originals: {n} non-JPEG skipped, screen only",
    wProg: "Writing originals {a}/{b}...",
    wDone: "Originals written: {ok} ok{fail} · promoted to GPS anchors",
    wDoneFail: ", {n} failed", wDoneSkip: ", {n} skipped",
    minTitle: "Collapse/expand", localTag: "(local)", emptyTrip: "No photos placed (shooting time needed)", compassTitle: "Reset north",
    heroTitle: "3D Travel Map — Walk Your Trip Again With Photos",
    heroD1: "Reads shooting time and GPS from your travel photos and draws the journey on a 3D globe in time order.",
    heroD2: "Photos without GPS are grouped at the same place — just pick a folder and the route, playback and day-by-day travel are ready.",
    heroD3: "Photos are read only inside your browser and never uploaded anywhere.",
    gpsOverwrite: "{n} photo(s) already have GPS values. Really overwrite them?",
    exifrFail: "exifr failed to load (check network)", noPhotos: "No photos/videos", wPiexif: "piexif failed to load", wVerify: "verification failed",
  },
  ja: {
    home: "⌂ ホーム", homeTitle: "旅行リスト",
    mapStreet: "🗺 一般", mapSat: "🛰 衛星", mapTerrain: "⛰ 地形", mapBld: "🏢 3D",
    tripsTitle: "旅行選択", localOpen: "📂 フォルダを開く",
    noTrips: "📂 ローカルのtravelフォルダを指定してください（写真はブラウザ内のみ、アップロードなし）",
    play: "▶ 再生", pause: "⏸ 停止", first: "⏮ 最初", firstTitle: "最初の写真へ",
    normal: "等倍", manualBtn: "📍 位置指定", manualBtnTitle: "GPSのない区間を手動で指定",
    heldChk: "推定表示", follow: "追跡",
    manualTitle: "📍 位置を手動指定", mqPh: "例： 清州国際空港", search: "検索",
    searching: "検索中...", noResult: "結果なし", searchFail: "検索失敗（ネットワーク）: ",
    placeFallback: "指定場所",
    scopeCurrent: "今の写真のみ", scopeBefore: "最初のGPSより前の写真すべて", scopeRange: "時間範囲",
    photoUnit: "枚",
    mnote: "指定場所が新しいアンカーになり前後の写真を再配置 · JPEGのEXIFにも記録（書き込み許可フォルダ）",
    apply: "適用", rulesTitle: "指定リスト", export: "書出", import: "読込",
    del: "削除", none: "なし", notArray: "配列ではない",
    scopeBeforeList: "最初のGPSより前すべて", photoOne: "写真: ",
    badgeGps: "GPS確定", badgeHeld: "同場所", badgeManual: "直接指定",
    segStay: "🚶 滞在", segWalk: "🚶 徒歩/滞在", segTransit: "🚇 乗物", segPlane: "✈️ 飛行機", segShip: "🚢 船",
    segManualFallback: "直接指定",
    day: "{n}日目", airport: "空港", stay: "宿泊",
    interlude: "{n}日目開始 — 起床＋荷造り",
    stats: "全体 {total} · GPS {gps} · 同場所 {held} · 直接 {manual} · {start} ~ {end}",
    infoTime: "時刻", infoMove: "移動", infoAt: "配置", infoFile: "ファイル",
    heic: "HEICプレビュー非対応", heicDl: "原本ダウンロード",
    mapIs: "地図: {x}", mapFailOver: "地図失敗 → {x}に切替", mapFailAll: "地図読込失敗（ネットワーク確認）",
    mapTileErr: "地図タイルエラー — ネットワーク確認", styleFail: "地図スタイル読込失敗 — 再読込してください",
    initFail: "初期化失敗: ",
    openFailRo: "フォルダを開けず読取専用で試行: ", reading: "読込中 {a}/{b}...", readFail: "読込失敗: ",
    gpsNoNeed: "GPS写真の指定は不要", needRange: "時間範囲を入力",
    importFail: "読込失敗: ",
    wNoPiexif: "原本記録不可: piexif読込失敗",
    wNoPerm: "原本記録不可: 書込権限なし（フォルダを開き直す） · {n}枚は画面のみ",
    wNoJpeg: "原本記録: JPEG以外{n}枚除外、画面のみ",
    wProg: "原本記録中 {a}/{b}...",
    wDone: "原本記録完了: 成功{ok}{fail} · GPSアンカーに昇格",
    wDoneFail: "、失敗{n}", wDoneSkip: "、除外{n}",
    minTitle: "折畳み/展開", localTag: "(ローカル)", emptyTrip: "配置できる写真なし（撮影時刻が必要）", compassTitle: "北へリセット",
    heroTitle: "3D旅行地図 — 写真でもう一度旅を歩く",
    heroD1: "旅行写真の撮影時刻とGPSを読み取り、3D地球儀の上に時系列の旅行ルートを自動で描きます。",
    heroD2: "GPSのない写真は同じ場所にまとめ、フォルダを指定するだけでルート・再生・日別移動が完成します。",
    heroD3: "写真はブラウザ内でのみ読み取られ、どこにもアップロードされません。",
    gpsOverwrite: "GPS値を持つ写真が{n}枚含まれています。本当に上書きしますか？",
    exifrFail: "exifr読込失敗（ネットワーク確認）", noPhotos: "写真/動画なし", wPiexif: "piexif読込失敗", wVerify: "検証失敗",
  },
  zh: {
    home: "⌂ 首页", homeTitle: "旅行列表",
    mapStreet: "🗺 普通", mapSat: "🛰 卫星", mapTerrain: "⛰ 地形", mapBld: "🏢 3D",
    tripsTitle: "选择旅行", localOpen: "📂 打开文件夹",
    noTrips: "📂 指定本地 travel 文件夹（照片仅在浏览器中读取，不上传）",
    play: "▶ 播放", pause: "⏸ 暂停", first: "⏮ 开头", firstTitle: "回到第一张照片",
    normal: "正常速度", manualBtn: "📍 指定位置", manualBtnTitle: "手动指定无GPS区段的位置",
    heldChk: "显示估计", follow: "跟随",
    manualTitle: "📍 手动指定位置", mqPh: "例： 清州国际机场", search: "搜索",
    searching: "搜索中...", noResult: "无结果", searchFail: "搜索失败（网络）: ",
    placeFallback: "指定地点",
    scopeCurrent: "仅当前照片", scopeBefore: "首个GPS之前的所有照片", scopeRange: "时间范围",
    photoUnit: "张",
    mnote: "指定地点将成为新锚点，前后照片重新归位 · 同时写入JPEG EXIF（需可写文件夹）",
    apply: "应用", rulesTitle: "指定列表", export: "导出", import: "导入",
    del: "删除", none: "无", notArray: "不是数组",
    scopeBeforeList: "首个GPS之前全部", photoOne: "照片: ",
    badgeGps: "GPS确定", badgeHeld: "同地点", badgeManual: "直接指定",
    segStay: "🚶 停留", segWalk: "🚶 步行/停留", segTransit: "🚇 交通工具", segPlane: "✈️ 飞机", segShip: "🚢 船",
    segManualFallback: "直接指定",
    day: "第{n}天", airport: "机场", stay: "住宿",
    interlude: "第{n}天开始 — 起床＋收拾行李",
    stats: "共 {total} · GPS {gps} · 同地点 {held} · 直接 {manual} · {start} ~ {end}",
    infoTime: "时间", infoMove: "移动", infoAt: "位置", infoFile: "文件",
    heic: "不支持HEIC预览", heicDl: "下载原图",
    mapIs: "地图: {x}", mapFailOver: "地图失败 → 切换到{x}", mapFailAll: "地图加载失败（检查网络）",
    mapTileErr: "地图瓦片错误 — 检查网络", styleFail: "地图样式加载失败 — 请刷新",
    initFail: "初始化失败: ",
    openFailRo: "文件夹打开失败，尝试只读: ", reading: "读取中 {a}/{b}...", readFail: "读取失败: ",
    gpsNoNeed: "GPS照片无需指定", needRange: "请输入时间范围",
    importFail: "导入失败: ",
    wNoPiexif: "无法写入原图: piexif加载失败",
    wNoPerm: "无法写入原图: 无写入权限（重新打开文件夹） · {n}张仅显示",
    wNoJpeg: "原图: {n}张非JPEG除外，仅显示",
    wProg: "正在写入原图 {a}/{b}...",
    wDone: "原图写入完成: 成功{ok}{fail} · 已升级为GPS锚点",
    wDoneFail: "、失败{n}", wDoneSkip: "、跳过{n}",
    minTitle: "折叠/展开", localTag: "(本地)", emptyTrip: "没有可放置的照片（需要拍摄时间）", compassTitle: "指向北方",
    heroTitle: "3D旅行地图 — 用照片重走旅途",
    heroD1: "读取旅行照片的拍摄时间和GPS，在3D地球仪上按时间顺序自动绘制旅行路线。",
    heroD2: "没有GPS的照片会归到同一地点，只需指定文件夹，路线、播放、逐日行程自动完成。",
    heroD3: "照片仅在浏览器内读取，不会上传到任何地方。",
    gpsOverwrite: "其中有{n}张照片已有GPS值，真的要覆盖吗？",
    exifrFail: "exifr加载失败（检查网络）", noPhotos: "无照片/视频", wPiexif: "piexif加载失败", wVerify: "验证失败",
  },
};
let LANG = null;
try { LANG = localStorage.getItem("tm_lang") || null; } catch (e) {}
if (!STR[LANG]) LANG = null;
function T(key, params) {
  let s = (LANG && STR[LANG] && STR[LANG][key]) ?? STR.ko[key] ?? key;
  if (params) for (const k in params) s = s.replace("{" + k + "}", params[k]);
  return s;
}
function setLang(l) {
  if (!STR[l]) return;
  LANG = l;
  try { localStorage.setItem("tm_lang", l); } catch (e) {}
  document.documentElement.lang = l === "zh" ? "zh-CN" : l === "ja" ? "ja" : l;
  document.querySelectorAll("[data-i18n]").forEach(el => { el.textContent = T(el.dataset.i18n); });
  document.querySelectorAll("[data-i18n-ph]").forEach(el => { el.placeholder = T(el.dataset.i18nPh); });
  document.querySelectorAll("[data-i18n-title]").forEach(el => { el.title = T(el.dataset.i18nTitle); });
  const sel = document.getElementById("langSel");
  if (sel) sel.value = l;
  shownDay = null;
  if (typeof renderRules === "function" && typeof TL !== "undefined" && TL) renderRules();
  if (typeof TL !== "undefined" && TL && typeof renderAll === "function") renderAll(idx);
}
