// UI strings: ko / en / ja / zh
const LANGS = ["ko", "en", "ja", "zh", "es", "fr", "de", "pt", "it", "ru", "th", "vi", "id"];
const LANG_NAMES = { ko: "한국어", en: "English", ja: "日本語", zh: "中文" };
const STR = {
  ko: {
    home: "⌂ 홈", homeTitle: "여행 목록",
    mapStreet: "🗺 일반", mapSat: "🛰 위성", mapTerrain: "⛰ 지형", mapBld: "🏢 3D",
    tripsTitle: "여행 선택", localOpen: "📂 내 폴더 열기",
    noTrips: "📂 내 폴더 열기로 로컬 travel 폴더를 지정하세요 (사진은 브라우저에서만 읽고 업로드되지 않음)",
    play: "▶ 재생", pause: "⏸ 정지", first: "⏮ 처음", firstTitle: "첫 사진 위치로",
    normal: "정배속", manualBtn: "📍 위치지정", manualBtnTitle: "GPS 없는 구간 위치 직접 지정",
    heldChk: "추정 표시", follow: "따라가기",
    manualTitle: "📍 위치 직접 지정", mqPh: "예: 청주국제공항", search: "검색",
    searching: "검색 중...", noResult: "결과 없음", searchFail: "검색 실패(네트워크): ",
    placeFallback: "지정위치",
    scopeCurrent: "지금 보고 있는 사진 1장", scopeBefore: "첫 GPS 이전 사진 전부", scopeRange: "시간 범위 지정",
    photoUnit: "장",
    mnote: "지정한 위치가 새 앵커가 되어 앞뒤 사진이 규칙대로 재배치됨 · JPEG 원본 EXIF에도 기록 (쓰기 허용 폴더)",
    apply: "적용", rulesTitle: "지정 목록", export: "내보내기", import: "가져오기",
    del: "삭제", none: "없음", notArray: "배열 아님",
    scopeBeforeList: "첫 GPS 이전 전부", photoOne: "사진 1장: ",
    badgeGps: "GPS확정", badgeHeld: "같은장소", badgeManual: "직접지정",
    segStay: "🚶 체류", segWalk: "🚶 도보/체류", segTransit: "🚇 탈것", segPlane: "✈️ 비행기", segShip: "🚢 배",
    segManualFallback: "직접지정",
    day: "{n}일차", airport: "공항", stay: "숙소",
    interlude: "{n}일차 시작 — 기상 + 짐싸기",
    stats: "전체 {total} · GPS {gps} · 같은장소 {held} · 직접 {manual} · {start} ~ {end}",
    infoTime: "시간", infoMove: "이동", infoAt: "배치", infoFile: "파일",
    heic: "HEIC 미리보기 미지원", heicDl: "원본 다운로드",
    mapIs: "지도: {x}", mapFailOver: "지도 실패 → {x}로 전환", mapFailAll: "지도 로드 실패 (네트워크 확인 필요)",
    mapTileErr: "지도 타일 오류 — 네트워크 확인", styleFail: "지도 스타일 로드 실패 — 새로고침 해주세요",
    initFail: "초기화 실패: ",
    openFailRo: "폴더 열기 실패, 읽기 전용으로 시도: ", reading: "읽는 중 {a}/{b}...", readFail: "읽기 실패: ",
    gpsNoNeed: "GPS 확정 사진은 지정할 필요 없음", needRange: "시간 범위를 입력하세요",
    importFail: "가져오기 실패: ",
    wNoPiexif: "원본 기록 불가: piexif 로드 실패",
    wNoPerm: "원본 기록 불가: 쓰기 권한 없음(폴더를 다시 열어 허용) · {n}장 화면에만 적용",
    wNoJpeg: "원본 기록: JPEG 아님 {n}장 제외, 화면에만 적용",
    wProg: "원본 기록 중 {a}/{b}...",
    wDone: "원본 기록 완료: 성공 {ok}{fail} · GPS 앵커 승격",
    wDoneFail: ", 실패 {n}", wDoneSkip: ", 제외 {n}",
    minTitle: "접기/펼치기", localTag: "(내 폴더)", emptyTrip: "배치된 사진 없음 (촬영 시간 정보 필요)", compassTitle: "북쪽으로", moverBtn: "🚶 아이콘",
    heroTitle: "3D 여행 지도 — 사진으로 다시 걷는 여행",
    heroD1: "여행 사진 속 촬영 시간과 GPS를 읽어 3D 지구본 위에 시간순 여행 경로를 자동으로 그립니다.",
    heroD2: "GPS가 없는 사진은 같은 장소에 모아두고, 폴더를 지정하는 것만으로 경로·재생·일차별 이동이 완성됩니다.",
    heroD3: "사진은 브라우저에서만 읽고 어디에도 업로드되지 않습니다.",
    gpsOverwrite: "이미 GPS 값이 있는 사진 {n}장이 포함되어 있습니다. 진짜로 덮어씌우시겠습니까?",
    exifrFail: "exifr 로드 실패(네트워크 확인)", noPhotos: "사진/영상이 없음", wPiexif: "piexif 로드 실패", wVerify: "검증 실패",
  },
  en: {
    home: "⌂ Home", homeTitle: "Trip list",
    mapStreet: "🗺 Streets", mapSat: "🛰 Satellite", mapTerrain: "⛰ Terrain", mapBld: "🏢 3D",
    tripsTitle: "Select trip", localOpen: "📂 Open folder",
    noTrips: "📂 Open a local travel folder (photos stay in your browser, nothing is uploaded)",
    play: "▶ Play", pause: "⏸ Pause", first: "⏮ Start", firstTitle: "Go to first photo",
    normal: "1x", manualBtn: "📍 Set location", manualBtnTitle: "Manually set location for no-GPS section",
    heldChk: "Show estimates", follow: "Follow",
    manualTitle: "📍 Set location manually", mqPh: "e.g. Cheongju Airport", search: "Search",
    searching: "Searching...", noResult: "No results", searchFail: "Search failed (network): ",
    placeFallback: "Pinned place",
    scopeCurrent: "Current photo only", scopeBefore: "All photos before first GPS", scopeRange: "Time range",
    photoUnit: " photos",
    mnote: "The pinned place becomes a new anchor and nearby photos are re-placed · Also written to JPEG EXIF (writable folder)",
    apply: "Apply", rulesTitle: "Saved", export: "Export", import: "Import",
    del: "Delete", none: "None", notArray: "Not an array",
    scopeBeforeList: "Everything before first GPS", photoOne: "Photo: ",
    badgeGps: "GPS", badgeHeld: "Placed", badgeManual: "Manual",
    segStay: "🚶 Stay", segWalk: "🚶 Walk/stay", segTransit: "🚇 Transit", segPlane: "✈️ Flight", segShip: "🚢 Ferry",
    segManualFallback: "Manual",
    day: "Day {n}", airport: "Airport", stay: "Stay",
    interlude: "Day {n} start — wake up + pack",
    stats: "Total {total} · GPS {gps} · Placed {held} · Manual {manual} · {start} ~ {end}",
    infoTime: "Time", infoMove: "Move", infoAt: "At", infoFile: "File",
    heic: "HEIC preview unsupported", heicDl: "Download original",
    mapIs: "Map: {x}", mapFailOver: "Map failed → switched to {x}", mapFailAll: "Map load failed (check network)",
    mapTileErr: "Map tile error — check network", styleFail: "Map style load failed — please reload",
    initFail: "Init failed: ",
    openFailRo: "Folder open failed, trying read-only: ", reading: "Reading {a}/{b}...", readFail: "Read failed: ",
    gpsNoNeed: "GPS photos need no manual pin", needRange: "Enter a time range",
    importFail: "Import failed: ",
    wNoPiexif: "Cannot write originals: piexif failed to load",
    wNoPerm: "Cannot write originals: no write permission (reopen the folder) · {n} shown on screen only",
    wNoJpeg: "Originals: {n} non-JPEG skipped, screen only",
    wProg: "Writing originals {a}/{b}...",
    wDone: "Originals written: {ok} ok{fail} · promoted to GPS anchors",
    wDoneFail: ", {n} failed", wDoneSkip: ", {n} skipped",
    minTitle: "Collapse/expand", localTag: "(local)", emptyTrip: "No photos placed (shooting time needed)", compassTitle: "Reset north", moverBtn: "🚶 Icons",
    heroTitle: "3D Travel Map — Walk Your Trip Again With Photos",
    heroD1: "Reads shooting time and GPS from your travel photos and draws the journey on a 3D globe in time order.",
    heroD2: "Photos without GPS are grouped at the same place — just pick a folder and the route, playback and day-by-day travel are ready.",
    heroD3: "Photos are read only inside your browser and never uploaded anywhere.",
    gpsOverwrite: "{n} photo(s) already have GPS values. Really overwrite them?",
    exifrFail: "exifr failed to load (check network)", noPhotos: "No photos/videos", wPiexif: "piexif failed to load", wVerify: "verification failed",
  },
  ja: {
    home: "⌂ ホーム", homeTitle: "旅行リスト",
    mapStreet: "🗺 一般", mapSat: "🛰 衛星", mapTerrain: "⛰ 地形", mapBld: "🏢 3D",
    tripsTitle: "旅行選択", localOpen: "📂 フォルダを開く",
    noTrips: "📂 ローカルのtravelフォルダを指定してください（写真はブラウザ内のみ、アップロードなし）",
    play: "▶ 再生", pause: "⏸ 停止", first: "⏮ 最初", firstTitle: "最初の写真へ",
    normal: "等倍", manualBtn: "📍 位置指定", manualBtnTitle: "GPSのない区間を手動で指定",
    heldChk: "推定表示", follow: "追跡",
    manualTitle: "📍 位置を手動指定", mqPh: "例： 清州国際空港", search: "検索",
    searching: "検索中...", noResult: "結果なし", searchFail: "検索失敗（ネットワーク）: ",
    placeFallback: "指定場所",
    scopeCurrent: "今の写真のみ", scopeBefore: "最初のGPSより前の写真すべて", scopeRange: "時間範囲",
    photoUnit: "枚",
    mnote: "指定場所が新しいアンカーになり前後の写真を再配置 · JPEGのEXIFにも記録（書き込み許可フォルダ）",
    apply: "適用", rulesTitle: "指定リスト", export: "書出", import: "読込",
    del: "削除", none: "なし", notArray: "配列ではない",
    scopeBeforeList: "最初のGPSより前すべて", photoOne: "写真: ",
    badgeGps: "GPS確定", badgeHeld: "同場所", badgeManual: "直接指定",
    segStay: "🚶 滞在", segWalk: "🚶 徒歩/滞在", segTransit: "🚇 乗物", segPlane: "✈️ 飛行機", segShip: "🚢 船",
    segManualFallback: "直接指定",
    day: "{n}日目", airport: "空港", stay: "宿泊",
    interlude: "{n}日目開始 — 起床＋荷造り",
    stats: "全体 {total} · GPS {gps} · 同場所 {held} · 直接 {manual} · {start} ~ {end}",
    infoTime: "時刻", infoMove: "移動", infoAt: "配置", infoFile: "ファイル",
    heic: "HEICプレビュー非対応", heicDl: "原本ダウンロード",
    mapIs: "地図: {x}", mapFailOver: "地図失敗 → {x}に切替", mapFailAll: "地図読込失敗（ネットワーク確認）",
    mapTileErr: "地図タイルエラー — ネットワーク確認", styleFail: "地図スタイル読込失敗 — 再読込してください",
    initFail: "初期化失敗: ",
    openFailRo: "フォルダを開けず読取専用で試行: ", reading: "読込中 {a}/{b}...", readFail: "読込失敗: ",
    gpsNoNeed: "GPS写真の指定は不要", needRange: "時間範囲を入力",
    importFail: "読込失敗: ",
    wNoPiexif: "原本記録不可: piexif読込失敗",
    wNoPerm: "原本記録不可: 書込権限なし（フォルダを開き直す） · {n}枚は画面のみ",
    wNoJpeg: "原本記録: JPEG以外{n}枚除外、画面のみ",
    wProg: "原本記録中 {a}/{b}...",
    wDone: "原本記録完了: 成功{ok}{fail} · GPSアンカーに昇格",
    wDoneFail: "、失敗{n}", wDoneSkip: "、除外{n}",
    minTitle: "折畳み/展開", localTag: "(ローカル)", emptyTrip: "配置できる写真なし（撮影時刻が必要）", compassTitle: "北へリセット", moverBtn: "🚶 アイコン",
    heroTitle: "3D旅行地図 — 写真でもう一度旅を歩く",
    heroD1: "旅行写真の撮影時刻とGPSを読み取り、3D地球儀の上に時系列の旅行ルートを自動で描きます。",
    heroD2: "GPSのない写真は同じ場所にまとめ、フォルダを指定するだけでルート・再生・日別移動が完成します。",
    heroD3: "写真はブラウザ内でのみ読み取られ、どこにもアップロードされません。",
    gpsOverwrite: "GPS値を持つ写真が{n}枚含まれています。本当に上書きしますか？",
    exifrFail: "exifr読込失敗（ネットワーク確認）", noPhotos: "写真/動画なし", wPiexif: "piexif読込失敗", wVerify: "検証失敗",
  },
  zh: {
    home: "⌂ 首页", homeTitle: "旅行列表",
    mapStreet: "🗺 普通", mapSat: "🛰 卫星", mapTerrain: "⛰ 地形", mapBld: "🏢 3D",
    tripsTitle: "选择旅行", localOpen: "📂 打开文件夹",
    noTrips: "📂 指定本地 travel 文件夹（照片仅在浏览器中读取，不上传）",
    play: "▶ 播放", pause: "⏸ 暂停", first: "⏮ 开头", firstTitle: "回到第一张照片",
    normal: "正常速度", manualBtn: "📍 指定位置", manualBtnTitle: "手动指定无GPS区段的位置",
    heldChk: "显示估计", follow: "跟随",
    manualTitle: "📍 手动指定位置", mqPh: "例： 清州国际机场", search: "搜索",
    searching: "搜索中...", noResult: "无结果", searchFail: "搜索失败（网络）: ",
    placeFallback: "指定地点",
    scopeCurrent: "仅当前照片", scopeBefore: "首个GPS之前的所有照片", scopeRange: "时间范围",
    photoUnit: "张",
    mnote: "指定地点将成为新锚点，前后照片重新归位 · 同时写入JPEG EXIF（需可写文件夹）",
    apply: "应用", rulesTitle: "指定列表", export: "导出", import: "导入",
    del: "删除", none: "无", notArray: "不是数组",
    scopeBeforeList: "首个GPS之前全部", photoOne: "照片: ",
    badgeGps: "GPS确定", badgeHeld: "同地点", badgeManual: "直接指定",
    segStay: "🚶 停留", segWalk: "🚶 步行/停留", segTransit: "🚇 交通工具", segPlane: "✈️ 飞机", segShip: "🚢 船",
    segManualFallback: "直接指定",
    day: "第{n}天", airport: "机场", stay: "住宿",
    interlude: "第{n}天开始 — 起床＋收拾行李",
    stats: "共 {total} · GPS {gps} · 同地点 {held} · 直接 {manual} · {start} ~ {end}",
    infoTime: "时间", infoMove: "移动", infoAt: "位置", infoFile: "文件",
    heic: "不支持HEIC预览", heicDl: "下载原图",
    mapIs: "地图: {x}", mapFailOver: "地图失败 → 切换到{x}", mapFailAll: "地图加载失败（检查网络）",
    mapTileErr: "地图瓦片错误 — 检查网络", styleFail: "地图样式加载失败 — 请刷新",
    initFail: "初始化失败: ",
    openFailRo: "文件夹打开失败，尝试只读: ", reading: "读取中 {a}/{b}...", readFail: "读取失败: ",
    gpsNoNeed: "GPS照片无需指定", needRange: "请输入时间范围",
    importFail: "导入失败: ",
    wNoPiexif: "无法写入原图: piexif加载失败",
    wNoPerm: "无法写入原图: 无写入权限（重新打开文件夹） · {n}张仅显示",
    wNoJpeg: "原图: {n}张非JPEG除外，仅显示",
    wProg: "正在写入原图 {a}/{b}...",
    wDone: "原图写入完成: 成功{ok}{fail} · 已升级为GPS锚点",
    wDoneFail: "、失败{n}", wDoneSkip: "、跳过{n}",
    minTitle: "折叠/展开", localTag: "(本地)", emptyTrip: "没有可放置的照片（需要拍摄时间）", compassTitle: "指向北方", moverBtn: "🚶 图标",
    heroTitle: "3D旅行地图 — 用照片重走旅途",
    heroD1: "读取旅行照片的拍摄时间和GPS，在3D地球仪上按时间顺序自动绘制旅行路线。",
    heroD2: "没有GPS的照片会归到同一地点，只需指定文件夹，路线、播放、逐日行程自动完成。",
    heroD3: "照片仅在浏览器内读取，不会上传到任何地方。",
    gpsOverwrite: "其中有{n}张照片已有GPS值，真的要覆盖吗？",
    exifrFail: "exifr加载失败（检查网络）", noPhotos: "无照片/视频", wPiexif: "piexif加载失败", wVerify: "验证失败",
  },
  es: {
    home: "⌂ Inicio", homeTitle: "Lista de viajes",
    mapStreet: "🗺 Callejero", mapSat: "🛰 Satélite", mapTerrain: "⛰ Relieve", mapBld: "🏢 3D",
    tripsTitle: "Elegir viaje", localOpen: "📂 Abrir carpeta",
    noTrips: "📂 Elige una carpeta travel local (las fotos solo se leen en tu navegador, no se suben)",
    play: "▶ Reproducir", pause: "⏸ Pausar", first: "⏮ Inicio", firstTitle: "Ir a la primera foto",
    normal: "1x", manualBtn: "📍 Fijar lugar", manualBtnTitle: "Fijar manualmente un tramo sin GPS",
    heldChk: "Mostrar estimados", follow: "Seguir",
    manualTitle: "📍 Fijar lugar manualmente", mqPh: "p. ej., Aeropuerto de Cheongju", search: "Buscar",
    searching: "Buscando...", noResult: "Sin resultados", searchFail: "Búsqueda fallida (red): ",
    placeFallback: "Lugar fijado",
    scopeCurrent: "Solo la foto actual", scopeBefore: "Todas las fotos antes del primer GPS", scopeRange: "Rango de tiempo",
    photoUnit: " fotos",
    mnote: "El lugar fijado se vuelve un ancla nueva y recoloca las fotos cercanas · También se escribe en el EXIF JPEG (carpeta con escritura)",
    apply: "Aplicar", rulesTitle: "Guardados", export: "Exportar", import: "Importar",
    del: "Borrar", none: "Ninguno", notArray: "No es un arreglo",
    scopeBeforeList: "Todo antes del primer GPS", photoOne: "Foto: ",
    badgeGps: "GPS", badgeHeld: "Ubicado", badgeManual: "Manual",
    segStay: "🚶 Parada", segWalk: "🚶 A pie/parada", segTransit: "🚇 Transporte", segPlane: "✈️ Vuelo", segShip: "🚢 Barco",
    segManualFallback: "Manual",
    day: "Día {n}", airport: "Aeropuerto", stay: "Alojamiento",
    interlude: "Día {n}: despertar + equipaje",
    stats: "Total {total} · GPS {gps} · Ubicados {held} · Manual {manual} · {start} ~ {end}",
    infoTime: "Hora", infoMove: "Tramo", infoAt: "En", infoFile: "Archivo",
    heic: "Vista HEIC no compatible", heicDl: "Descargar original",
    mapIs: "Mapa: {x}", mapFailOver: "Mapa falló → {x}", mapFailAll: "Mapa no carga (revisa la red)",
    mapTileErr: "Error de teselas — revisa la red", styleFail: "Estilo no carga — recarga la página",
    initFail: "Error inicial: ",
    openFailRo: "No se pudo abrir, probando solo lectura: ", reading: "Leyendo {a}/{b}...", readFail: "Lectura fallida: ",
    gpsNoNeed: "Las fotos GPS no necesitan fijado", needRange: "Indica un rango de tiempo",
    importFail: "Importación fallida: ",
    wNoPiexif: "No se puede escribir: piexif no cargó",
    wNoPerm: "Sin permiso de escritura (reabre la carpeta) · {n} solo en pantalla",
    wNoJpeg: "Originales: {n} no-JPEG omitidos, solo pantalla",
    wProg: "Escribiendo originales {a}/{b}...",
    wDone: "Originales listos: {ok} bien{fail} · anclas GPS",
    wDoneFail: ", {n} mal", wDoneSkip: ", {n} omitidos",
    minTitle: "Plegar/desplegar", localTag: "(local)", emptyTrip: "Sin fotos ubicadas (falta hora de disparo)", compassTitle: "Norte", moverBtn: "🚶 Iconos",
    heroTitle: "Mapa de viaje 3D — revive tu viaje con fotos",
    heroD1: "Lee la hora y el GPS de tus fotos y dibuja la ruta en un globo 3D en orden de tiempo.",
    heroD2: "Las fotos sin GPS se agrupan en el mismo lugar: elige una carpeta y listo.",
    heroD3: "Las fotos solo se leen en tu navegador, nunca se suben.",
    gpsOverwrite: "{n} foto(s) ya tienen GPS. ¿Sobrescribir de verdad?",
    exifrFail: "exifr no cargó (revisa la red)", noPhotos: "Sin fotos/videos", wPiexif: "piexif no cargó", wVerify: "verificación fallida",
  },
  fr: {
    home: "⌂ Accueil", homeTitle: "Liste des voyages",
    mapStreet: "🗺 Plan", mapSat: "🛰 Satellite", mapTerrain: "⛰ Relief", mapBld: "🏢 3D",
    tripsTitle: "Choisir un voyage", localOpen: "📂 Ouvrir un dossier",
    noTrips: "📂 Choisissez un dossier travel local (photos lues dans le navigateur, rien n'est envoyé)",
    play: "▶ Lecture", pause: "⏸ Pause", first: "⏮ Début", firstTitle: "Aller à la première photo",
    normal: "1x", manualBtn: "📍 Fixer un lieu", manualBtnTitle: "Fixer manuellement un tronçon sans GPS",
    heldChk: "Afficher estimations", follow: "Suivre",
    manualTitle: "📍 Fixer un lieu manuellement", mqPh: "ex. Aéroport de Cheongju", search: "Chercher",
    searching: "Recherche...", noResult: "Aucun résultat", searchFail: "Échec de recherche (réseau) : ",
    placeFallback: "Lieu épinglé",
    scopeCurrent: "Photo actuelle seule", scopeBefore: "Photos avant le premier GPS", scopeRange: "Plage horaire",
    photoUnit: " photos",
    mnote: "Le lieu épinglé devient une ancre et replace les photos voisines · Aussi écrit dans l'EXIF JPEG (dossier inscriptible)",
    apply: "Appliquer", rulesTitle: "Enregistrés", export: "Exporter", import: "Importer",
    del: "Supprimer", none: "Aucun", notArray: "Pas un tableau",
    scopeBeforeList: "Tout avant le premier GPS", photoOne: "Photo : ",
    badgeGps: "GPS", badgeHeld: "Placé", badgeManual: "Manuel",
    segStay: "🚶 Pause", segWalk: "🚶 À pied/pause", segTransit: "🚇 Transport", segPlane: "✈️ Vol", segShip: "🚢 Bateau",
    segManualFallback: "Manuel",
    day: "Jour {n}", airport: "Aéroport", stay: "Logement",
    interlude: "Jour {n} : réveil + bagages",
    stats: "Total {total} · GPS {gps} · Placés {held} · Manuel {manual} · {start} ~ {end}",
    infoTime: "Heure", infoMove: "Tronçon", infoAt: "À", infoFile: "Fichier",
    heic: "Aperçu HEIC indisponible", heicDl: "Télécharger l'original",
    mapIs: "Carte : {x}", mapFailOver: "Carte en échec → {x}", mapFailAll: "Carte non chargée (réseau ?)",
    mapTileErr: "Erreur de tuiles — vérifiez le réseau", styleFail: "Style non chargé — rechargez",
    initFail: "Échec init : ",
    openFailRo: "Ouverture impossible, lecture seule : ", reading: "Lecture {a}/{b}...", readFail: "Lecture échouée : ",
    gpsNoNeed: "Photos GPS : épinglage inutile", needRange: "Indiquez une plage horaire",
    importFail: "Import échoué : ",
    wNoPiexif: "Écriture impossible : piexif non chargé",
    wNoPerm: "Écriture impossible : autorisation requise (rouvrez le dossier) · {n} à l'écran seulement",
    wNoJpeg: "Originaux : {n} non-JPEG ignorés, écran seulement",
    wProg: "Écriture originaux {a}/{b}...",
    wDone: "Originaux écrits : {ok} ok{fail} · ancres GPS",
    wDoneFail: ", {n} ratés", wDoneSkip: ", {n} ignorés",
    minTitle: "Réduire/agrandir", localTag: "(local)", emptyTrip: "Aucune photo placée (heure requise)", compassTitle: "Nord", moverBtn: "🚶 Icônes",
    heroTitle: "Carte de voyage 3D — revivez vos voyages en photos",
    heroD1: "Lit l'heure et le GPS de vos photos et trace le parcours sur un globe 3D dans l'ordre du temps.",
    heroD2: "Les photos sans GPS sont regroupées au même endroit : choisissez un dossier, c'est prêt.",
    heroD3: "Les photos sont lues dans votre navigateur uniquement, jamais envoyées.",
    gpsOverwrite: "{n} photo(s) ont déjà un GPS. Vraiment écraser ?",
    exifrFail: "exifr non chargé (réseau ?)", noPhotos: "Ni photos ni vidéos", wPiexif: "piexif non chargé", wVerify: "vérification échouée",
  },
  de: {
    home: "⌂ Start", homeTitle: "Reiseliste",
    mapStreet: "🗺 Karte", mapSat: "🛰 Satellit", mapTerrain: "⛰ Gelände", mapBld: "🏢 3D",
    tripsTitle: "Reise wählen", localOpen: "📂 Ordner öffnen",
    noTrips: "📂 Lokalen travel-Ordner wählen (Fotos bleiben im Browser, kein Upload)",
    play: "▶ Abspielen", pause: "⏸ Pause", first: "⏮ Anfang", firstTitle: "Zum ersten Foto",
    normal: "1x", manualBtn: "📍 Ort setzen", manualBtnTitle: "Abschnitt ohne GPS manuell setzen",
    heldChk: "Schätzung zeigen", follow: "Folgen",
    manualTitle: "📍 Ort manuell setzen", mqPh: "z. B. Flughafen Cheongju", search: "Suchen",
    searching: "Suche...", noResult: "Keine Treffer", searchFail: "Suche fehlgeschlagen (Netz): ",
    placeFallback: "Gesetzter Ort",
    scopeCurrent: "Nur aktuelles Foto", scopeBefore: "Alle Fotos vor dem ersten GPS", scopeRange: "Zeitraum",
    photoUnit: " Fotos",
    mnote: "Der gesetzte Ort wird ein neuer Anker und ordnet Fotos neu zu · Auch ins JPEG-EXIF geschrieben (beschreibbarer Ordner)",
    apply: "Anwenden", rulesTitle: "Gespeichert", export: "Export", import: "Import",
    del: "Löschen", none: "Keine", notArray: "Kein Array",
    scopeBeforeList: "Alles vor dem ersten GPS", photoOne: "Foto: ",
    badgeGps: "GPS", badgeHeld: "Eingeordnet", badgeManual: "Manuell",
    segStay: "🚶 Stopp", segWalk: "🚶 Zu Fuß/Stopp", segTransit: "🚇 Verkehr", segPlane: "✈️ Flug", segShip: "🚢 Schiff",
    segManualFallback: "Manuell",
    day: "Tag {n}", airport: "Flughafen", stay: "Unterkunft",
    interlude: "Tag {n}: Aufwachen + Packen",
    stats: "Gesamt {total} · GPS {gps} · Eingeordnet {held} · Manuell {manual} · {start} ~ {end}",
    infoTime: "Zeit", infoMove: "Etappe", infoAt: "Bei", infoFile: "Datei",
    heic: "HEIC-Vorschau nicht möglich", heicDl: "Original laden",
    mapIs: "Karte: {x}", mapFailOver: "Karte fehlerhaft → {x}", mapFailAll: "Karte lädt nicht (Netz prüfen)",
    mapTileErr: "Kachelfehler — Netz prüfen", styleFail: "Stil lädt nicht — neu laden",
    initFail: "Init fehlgeschlagen: ",
    openFailRo: "Öffnen fehlgeschlagen, nur Lesen: ", reading: "Lese {a}/{b}...", readFail: "Lesen fehlgeschlagen: ",
    gpsNoNeed: "GPS-Fotos brauchen keinen Pin", needRange: "Zeitraum eingeben",
    importFail: "Import fehlgeschlagen: ",
    wNoPiexif: "Schreiben unmöglich: piexif fehlt",
    wNoPerm: "Schreiben unmöglich: keine Rechte (Ordner neu öffnen) · {n} nur Bildschirm",
    wNoJpeg: "Originale: {n} Nicht-JPEG übersprungen, nur Bildschirm",
    wProg: "Schreibe Originale {a}/{b}...",
    wDone: "Originale fertig: {ok} ok{fail} · GPS-Anker",
    wDoneFail: ", {n} Fehler", wDoneSkip: ", {n} übersprungen",
    minTitle: "Minimieren/Erweitern", localTag: "(lokal)", emptyTrip: "Keine Fotos eingeordnet (Zeit nötig)", compassTitle: "Norden", moverBtn: "🚶 Symbole",
    heroTitle: "3D-Reisekarte — Reise per Foto noch einmal gehen",
    heroD1: "Liest Zeit und GPS deiner Fotos und zeichnet die Route zeitlich sortiert auf einen 3D-Globus.",
    heroD2: "Fotos ohne GPS landen am gleichen Ort — Ordner wählen genügt.",
    heroD3: "Fotos bleiben im Browser, kein Upload.",
    gpsOverwrite: "{n} Foto(s) haben schon GPS. Wirklich überschreiben?",
    exifrFail: "exifr fehlt (Netz prüfen)", noPhotos: "Keine Fotos/Videos", wPiexif: "piexif fehlt", wVerify: "Prüfung fehlgeschlagen",
  },
  pt: {
    home: "⌂ Início", homeTitle: "Lista de viagens",
    mapStreet: "🗺 Mapa", mapSat: "🛰 Satélite", mapTerrain: "⛰ Relevo", mapBld: "🏢 3D",
    tripsTitle: "Escolher viagem", localOpen: "📂 Abrir pasta",
    noTrips: "📂 Escolha uma pasta travel local (fotos lidas no navegador, sem upload)",
    play: "▶ Tocar", pause: "⏸ Pausar", first: "⏮ Início", firstTitle: "Ir à primeira foto",
    normal: "1x", manualBtn: "📍 Fixar local", manualBtnTitle: "Fixar manualmente trecho sem GPS",
    heldChk: "Mostrar estimados", follow: "Seguir",
    manualTitle: "📍 Fixar local manualmente", mqPh: "ex. Aeroporto de Cheongju", search: "Buscar",
    searching: "Buscando...", noResult: "Sem resultados", searchFail: "Busca falhou (rede): ",
    placeFallback: "Local fixado",
    scopeCurrent: "Só a foto atual", scopeBefore: "Fotos antes do primeiro GPS", scopeRange: "Intervalo de tempo",
    photoUnit: " fotos",
    mnote: "O local fixado vira âncora nova e recoloca fotos · Também grava no EXIF JPEG (pasta com escrita)",
    apply: "Aplicar", rulesTitle: "Salvos", export: "Exportar", import: "Importar",
    del: "Apagar", none: "Nenhum", notArray: "Não é array",
    scopeBeforeList: "Tudo antes do primeiro GPS", photoOne: "Foto: ",
    badgeGps: "GPS", badgeHeld: "Locado", badgeManual: "Manual",
    segStay: "🚶 Parada", segWalk: "🚶 A pé/parada", segTransit: "🚇 Transporte", segPlane: "✈️ Voo", segShip: "🚢 Barco",
    segManualFallback: "Manual",
    day: "Dia {n}", airport: "Aeroporto", stay: "Hospedagem",
    interlude: "Dia {n}: acordar + arrumar",
    stats: "Total {total} · GPS {gps} · Locados {held} · Manual {manual} · {start} ~ {end}",
    infoTime: "Hora", infoMove: "Trecho", infoAt: "Em", infoFile: "Arquivo",
    heic: "Prévia HEIC indisponível", heicDl: "Baixar original",
    mapIs: "Mapa: {x}", mapFailOver: "Mapa falhou → {x}", mapFailAll: "Mapa não carrega (rede?)",
    mapTileErr: "Erro de tiles — ver rede", styleFail: "Estilo não carrega — recarregue",
    initFail: "Falha inicial: ",
    openFailRo: "Falha ao abrir, só leitura: ", reading: "Lendo {a}/{b}...", readFail: "Leitura falhou: ",
    gpsNoNeed: "Fotos GPS dispensam fixação", needRange: "Informe um intervalo",
    importFail: "Importação falhou: ",
    wNoPiexif: "Sem escrita: piexif não carregou",
    wNoPerm: "Sem escrita: sem permissão (reabra a pasta) · {n} só tela",
    wNoJpeg: "Originais: {n} não-JPEG pulados, só tela",
    wProg: "Escrevendo originais {a}/{b}...",
    wDone: "Originais prontos: {ok} ok{fail} · âncoras GPS",
    wDoneFail: ", {n} falha", wDoneSkip: ", {n} pulados",
    minTitle: "Recolher/expandir", localTag: "(local)", emptyTrip: "Sem fotos locadas (hora necessária)", compassTitle: "Norte", moverBtn: "🚶 Ícones",
    heroTitle: "Mapa de viagem 3D — reviva a viagem com fotos",
    heroD1: "Lê hora e GPS das fotos e desenha a rota num globo 3D em ordem de tempo.",
    heroD2: "Fotos sem GPS ficam no mesmo lugar — basta escolher a pasta.",
    heroD3: "Fotos lidas só no navegador, nunca enviadas.",
    gpsOverwrite: "{n} foto(s) já têm GPS. Sobrescrever mesmo?",
    exifrFail: "exifr não carregou (rede?)", noPhotos: "Sem fotos/vídeos", wPiexif: "piexif não carregou", wVerify: "verificação falhou",
  },
  it: {
    home: "⌂ Home", homeTitle: "Lista viaggi",
    mapStreet: "🗺 Mappa", mapSat: "🛰 Satellite", mapTerrain: "⛰ Rilievi", mapBld: "🏢 3D",
    tripsTitle: "Scegli viaggio", localOpen: "📂 Apri cartella",
    noTrips: "📂 Scegli una cartella travel locale (foto lette nel browser, nessun upload)",
    play: "▶ Play", pause: "⏸ Pausa", first: "⏮ Inizio", firstTitle: "Vai alla prima foto",
    normal: "1x", manualBtn: "📍 Fissa luogo", manualBtnTitle: "Fissa a mano un tratto senza GPS",
    heldChk: "Mostra stime", follow: "Segui",
    manualTitle: "📍 Fissa un luogo", mqPh: "es. Aeroporto di Cheongju", search: "Cerca",
    searching: "Ricerca...", noResult: "Nessun risultato", searchFail: "Ricerca fallita (rete): ",
    placeFallback: "Luogo fissato",
    scopeCurrent: "Solo foto attuale", scopeBefore: "Foto prima del primo GPS", scopeRange: "Intervallo",
    photoUnit: " foto",
    mnote: "Il luogo diventa un'ancora e riposiziona le foto · Scrive anche l'EXIF JPEG (cartella scrivibile)",
    apply: "Applica", rulesTitle: "Salvati", export: "Esporta", import: "Importa",
    del: "Elimina", none: "Nessuno", notArray: "Non è un array",
    scopeBeforeList: "Tutto prima del primo GPS", photoOne: "Foto: ",
    badgeGps: "GPS", badgeHeld: "Posizionata", badgeManual: "Manuale",
    segStay: "🚶 Sosta", segWalk: "🚶 A piedi/sosta", segTransit: "🚇 Mezzi", segPlane: "✈️ Volo", segShip: "🚢 Nave",
    segManualFallback: "Manuale",
    day: "Giorno {n}", airport: "Aeroporto", stay: "Alloggio",
    interlude: "Giorno {n}: sveglia + bagagli",
    stats: "Totale {total} · GPS {gps} · Posizionate {held} · Manuali {manual} · {start} ~ {end}",
    infoTime: "Ora", infoMove: "Tratto", infoAt: "A", infoFile: "File",
    heic: "Anteprima HEIC assente", heicDl: "Scarica originale",
    mapIs: "Mappa: {x}", mapFailOver: "Mappa fallita → {x}", mapFailAll: "Mappa non caricata (rete?)",
    mapTileErr: "Errore tile — controlla rete", styleFail: "Stile non caricato — ricarica",
    initFail: "Init fallita: ",
    openFailRo: "Apertura fallita, sola lettura: ", reading: "Lettura {a}/{b}...", readFail: "Lettura fallita: ",
    gpsNoNeed: "Foto GPS: fissaggio inutile", needRange: "Inserisci un intervallo",
    importFail: "Import fallito: ",
    wNoPiexif: "Scrittura impossibile: piexif assente",
    wNoPerm: "Scrittura impossibile: permessi (riapri cartella) · {n} solo schermo",
    wNoJpeg: "Originali: {n} non-JPEG saltati, solo schermo",
    wProg: "Scrivo originali {a}/{b}...",
    wDone: "Originali pronti: {ok} ok{fail} · ancore GPS",
    wDoneFail: ", {n} errori", wDoneSkip: ", {n} saltati",
    minTitle: "Riduci/espandi", localTag: "(locale)", emptyTrip: "Nessuna foto posizionata (ora necessaria)", compassTitle: "Nord", moverBtn: "🚶 Icone",
    heroTitle: "Mappa di viaggio 3D — rivivi il viaggio con le foto",
    heroD1: "Legge ora e GPS delle foto e disegna il percorso su un globo 3D in ordine di tempo.",
    heroD2: "Le foto senza GPS restano nello stesso posto: basta scegliere la cartella.",
    heroD3: "Foto lette solo nel browser, mai caricate.",
    gpsOverwrite: "{n} foto hanno già il GPS. Sovrascrivere davvero?",
    exifrFail: "exifr assente (rete?)", noPhotos: "Né foto né video", wPiexif: "piexif assente", wVerify: "verifica fallita",
  },
  ru: {
    home: "⌂ Главная", homeTitle: "Список поездок",
    mapStreet: "🗺 Карта", mapSat: "🛰 Спутник", mapTerrain: "⛰ Рельеф", mapBld: "🏢 3D",
    tripsTitle: "Выбрать поездку", localOpen: "📂 Открыть папку",
    noTrips: "📂 Выберите локальную папку travel (фото читаются в браузере, без загрузки)",
    play: "▶ Старт", pause: "⏸ Пауза", first: "⏮ Начало", firstTitle: "К первому фото",
    normal: "1x", manualBtn: "📍 Указать место", manualBtnTitle: "Вручную указать участок без GPS",
    heldChk: "Показывать оценки", follow: "Следить",
    manualTitle: "📍 Указать место вручную", mqPh: "напр., аэропорт Чхонджу", search: "Найти",
    searching: "Поиск...", noResult: "Ничего", searchFail: "Ошибка поиска (сеть): ",
    placeFallback: "Указанное место",
    scopeCurrent: "Только текущее фото", scopeBefore: "Фото до первого GPS", scopeRange: "Диапазон времени",
    photoUnit: " фото",
    mnote: "Место станет якорем и переместит фото · Также пишется в EXIF JPEG (папка с записью)",
    apply: "Готово", rulesTitle: "Сохранено", export: "Экспорт", import: "Импорт",
    del: "Удалить", none: "Нет", notArray: "Не массив",
    scopeBeforeList: "Всё до первого GPS", photoOne: "Фото: ",
    badgeGps: "GPS", badgeHeld: "Привязано", badgeManual: "Вручную",
    segStay: "🚶 Стоянка", segWalk: "🚶 Пешком/стоянка", segTransit: "🚇 Транспорт", segPlane: "✈️ Перелёт", segShip: "🚢 Паром",
    segManualFallback: "Вручную",
    day: "День {n}", airport: "Аэропорт", stay: "Ночлег",
    interlude: "День {n}: подъём + сборы",
    stats: "Всего {total} · GPS {gps} · Привязано {held} · Вручную {manual} · {start} ~ {end}",
    infoTime: "Время", infoMove: "Участок", infoAt: "Где", infoFile: "Файл",
    heic: "Превью HEIC нет", heicDl: "Скачать оригинал",
    mapIs: "Карта: {x}", mapFailOver: "Карта сбоит → {x}", mapFailAll: "Карта не грузится (сеть?)",
    mapTileErr: "Ошибка тайлов — проверь сеть", styleFail: "Стиль не загрузился — обнови",
    initFail: "Ошибка старта: ",
    openFailRo: "Не открыть, только чтение: ", reading: "Читаю {a}/{b}...", readFail: "Чтение провалено: ",
    gpsNoNeed: "GPS-фото не нуждаются", needRange: "Укажи диапазон",
    importFail: "Импорт провален: ",
    wNoPiexif: "Запись невозможна: нет piexif",
    wNoPerm: "Запись невозможна: нет прав (открой папку заново) · {n} только экран",
    wNoJpeg: "Оригиналы: {n} не-JPEG пропущены, только экран",
    wProg: "Пишу оригиналы {a}/{b}...",
    wDone: "Оригиналы готовы: {ok} ок{fail} · GPS-якоря",
    wDoneFail: ", {n} ошибок", wDoneSkip: ", {n} пропущено",
    minTitle: "Свернуть/развернуть", localTag: "(локально)", emptyTrip: "Фото не привязаны (нужно время)", compassTitle: "Север", moverBtn: "🚶 Значки",
    heroTitle: "3D-карта путешествий — пройди поездку заново по фото",
    heroD1: "Читает время и GPS фото и рисует маршрут на 3D-глобусе по порядку времени.",
    heroD2: "Фото без GPS остаются на месте — достаточно выбрать папку.",
    heroD3: "Фото читаются только в браузере и никуда не загружаются.",
    gpsOverwrite: "У {n} фото уже есть GPS. Точно перезаписать?",
    exifrFail: "exifr не загрузился (сеть?)", noPhotos: "Нет фото/видео", wPiexif: "piexif не загрузился", wVerify: "проверка провалена",
  },
  th: {
    home: "⌂ หน้าแรก", homeTitle: "รายการทริป",
    mapStreet: "🗺 แผนที่", mapSat: "🛰 ดาวเทียม", mapTerrain: "⛰ ภูมิประเทศ", mapBld: "🏢 3D",
    tripsTitle: "เลือกทริป", localOpen: "📂 เปิดโฟลเดอร์",
    noTrips: "📂 เลือกโฟลเดอร์ travel ในเครื่อง (อ่านรูปในเบราว์เซอร์เท่านั้น ไม่มีการอัปโหลด)",
    play: "▶ เล่น", pause: "⏸ หยุด", first: "⏮ เริ่ม", firstTitle: "ไปรูปแรก",
    normal: "1x", manualBtn: "📍 ปักหมุด", manualBtnTitle: "ปักหมุดช่วงที่ไม่มี GPS เอง",
    heldChk: "แสดงค่าประมาณ", follow: "ติดตาม",
    manualTitle: "📍 ปักหมุดเอง", mqPh: "เช่น สนามบินชองจู", search: "ค้นหา",
    searching: "กำลังค้นหา...", noResult: "ไม่พบ", searchFail: "ค้นหาล้มเหลว (เน็ต): ",
    placeFallback: "จุดที่ปัก",
    scopeCurrent: "เฉพาะรูปนี้", scopeBefore: "รูปก่อน GPS แรกทั้งหมด", scopeRange: "ช่วงเวลา",
    photoUnit: " รูป",
    mnote: "จุดที่ปักจะเป็นหมุดใหม่และจัดรูปใหม่ · เขียนลง EXIF JPEG ด้วย (โฟลเดอร์ที่เขียนได้)",
    apply: "ตกลง", rulesTitle: "ที่บันทึก", export: "ส่งออก", import: "นำเข้า",
    del: "ลบ", none: "ไม่มี", notArray: "ไม่ใช่อาร์เรย์",
    scopeBeforeList: "ทั้งหมดก่อน GPS แรก", photoOne: "รูป: ",
    badgeGps: "GPS", badgeHeld: "ปักแล้ว", badgeManual: "เอง",
    segStay: "🚶 พัก", segWalk: "🚶 เดิน/พัก", segTransit: "🚇 ยานพาหนะ", segPlane: "✈️ เครื่องบิน", segShip: "🚢 เรือ",
    segManualFallback: "เอง",
    day: "วันที่ {n}", airport: "สนามบิน", stay: "ที่พัก",
    interlude: "วันที่ {n} เริ่ม — ตื่น + เก็บกระเป๋า",
    stats: "ทั้งหมด {total} · GPS {gps} · ปักแล้ว {held} · เอง {manual} · {start} ~ {end}",
    infoTime: "เวลา", infoMove: "ช่วง", infoAt: "ที่", infoFile: "ไฟล์",
    heic: "ดู HEIC ไม่ได้", heicDl: "โหลดต้นฉบับ",
    mapIs: "แผนที่: {x}", mapFailOver: "แผนที่ล้ม → {x}", mapFailAll: "โหลดแผนที่ไม่ได้ (เช็กเน็ต)",
    mapTileErr: "ไทล์ผิดพลาด — เช็กเน็ต", styleFail: "โหลดสไตล์ไม่ได้ — รีเฟรช",
    initFail: "เริ่มล้มเหลว: ",
    openFailRo: "เปิดไม่ได้ ลองอ่านอย่างเดียว: ", reading: "อ่าน {a}/{b}...", readFail: "อ่านล้มเหลว: ",
    gpsNoNeed: "รูป GPS ไม่ต้องปัก", needRange: "ใส่ช่วงเวลา",
    importFail: "นำเข้าล้มเหลว: ",
    wNoPiexif: "เขียนไม่ได้: ไม่มี piexif",
    wNoPerm: "เขียนไม่ได้: ไม่มีสิทธิ์ (เปิดโฟลเดอร์ใหม่) · {n} แค่จอ",
    wNoJpeg: "ต้นฉบับ: ข้าม {n} ที่ไม่ใช่ JPEG, แค่จอ",
    wProg: "เขียนต้นฉบับ {a}/{b}...",
    wDone: "เขียนเสร็จ: {ok} ok{fail} · หมุด GPS",
    wDoneFail: ", {n} พลาด", wDoneSkip: ", {n} ข้าม",
    minTitle: "ย่อ/ขยาย", localTag: "(ในเครื่อง)", emptyTrip: "ไม่มีรูปที่ปัก (ต้องการเวลา)", compassTitle: "เหนือ", moverBtn: "🚶 ไอคอน",
    heroTitle: "แผนที่ท่องเที่ยว 3D — เดินทริปอีกครั้งด้วยรูป",
    heroD1: "อ่านเวลาและ GPS จากรูปแล้ววาดเส้นทางบนลูกโลก 3D ตามเวลา.",
    heroD2: "รูปไม่มี GPS อยู่จุดเดิม — แค่เลือกโฟลเดอร์ก็เสร็จ.",
    heroD3: "รูปอ่านในเบราว์เซอร์เท่านั้น ไม่มีการอัปโหลด.",
    gpsOverwrite: "มี {n} รูปที่มี GPS แล้ว เขียนทับจริงหรือ?",
    exifrFail: "โหลด exifr ไม่ได้ (เช็กเน็ต)", noPhotos: "ไม่มีรูป/วิดีโอ", wPiexif: "โหลด piexif ไม่ได้", wVerify: "ตรวจไม่ผ่าน",
  },
  vi: {
    home: "⌂ Trang chủ", homeTitle: "Danh sách chuyến đi",
    mapStreet: "🗺 Bản đồ", mapSat: "🛰 Vệ tinh", mapTerrain: "⛰ Địa hình", mapBld: "🏢 3D",
    tripsTitle: "Chọn chuyến đi", localOpen: "📂 Mở thư mục",
    noTrips: "📂 Chọn thư mục travel trên máy (ảnh chỉ đọc trong trình duyệt, không tải lên)",
    play: "▶ Phát", pause: "⏸ Dừng", first: "⏮ Đầu", firstTitle: "Về ảnh đầu",
    normal: "1x", manualBtn: "📍 Ghim vị trí", manualBtnTitle: "Tự ghim đoạn không có GPS",
    heldChk: "Hiện ước lượng", follow: "Theo dõi",
    manualTitle: "📍 Tự ghim vị trí", mqPh: "vd. Sân bay Cheongju", search: "Tìm",
    searching: "Đang tìm...", noResult: "Không có", searchFail: "Tìm thất bại (mạng): ",
    placeFallback: "Điểm đã ghim",
    scopeCurrent: "Chỉ ảnh này", scopeBefore: "Ảnh trước GPS đầu", scopeRange: "Khoảng giờ",
    photoUnit: " ảnh",
    mnote: "Điểm ghim thành neo mới và sắp lại ảnh · Ghi cả vào EXIF JPEG (thư mục được ghi)",
    apply: "Xong", rulesTitle: "Đã lưu", export: "Xuất", import: "Nhập",
    del: "Xóa", none: "Không", notArray: "Không phải mảng",
    scopeBeforeList: "Tất cả trước GPS đầu", photoOne: "Ảnh: ",
    badgeGps: "GPS", badgeHeld: "Đã ghim", badgeManual: "Tay",
    segStay: "🚶 Nghỉ", segWalk: "🚶 Đi bộ/nghỉ", segTransit: "🚇 Xe", segPlane: "✈️ Bay", segShip: "🚢 Tàu",
    segManualFallback: "Tay",
    day: "Ngày {n}", airport: "Sân bay", stay: "Chỗ ở",
    interlude: "Ngày {n}: dậy + xếp đồ",
    stats: "Tổng {total} · GPS {gps} · Đã ghim {held} · Tay {manual} · {start} ~ {end}",
    infoTime: "Giờ", infoMove: "Chặng", infoAt: "Tại", infoFile: "File",
    heic: "Không xem HEIC được", heicDl: "Tải gốc",
    mapIs: "Bản đồ: {x}", mapFailOver: "Bản đồ lỗi → {x}", mapFailAll: "Không tải bản đồ (mạng?)",
    mapTileErr: "Lỗi tile — xem mạng", styleFail: "Style lỗi — tải lại",
    initFail: "Lỗi khởi tạo: ",
    openFailRo: "Mở lỗi, chỉ đọc: ", reading: "Đọc {a}/{b}...", readFail: "Đọc lỗi: ",
    gpsNoNeed: "Ảnh GPS khỏi ghim", needRange: "Nhập khoảng giờ",
    importFail: "Nhập lỗi: ",
    wNoPiexif: "Không ghi được: thiếu piexif",
    wNoPerm: "Không ghi được: thiếu quyền (mở lại thư mục) · {n} chỉ màn hình",
    wNoJpeg: "Gốc: bỏ {n} không-JPEG, chỉ màn hình",
    wProg: "Đang ghi gốc {a}/{b}...",
    wDone: "Ghi xong: {ok} ok{fail} · neo GPS",
    wDoneFail: ", {n} lỗi", wDoneSkip: ", {n} bỏ",
    minTitle: "Thu/phóng", localTag: "(máy)", emptyTrip: "Chưa ghim ảnh (cần giờ)", compassTitle: "Bắc", moverBtn: "🚶 Biểu tượng",
    heroTitle: "Bản đồ du lịch 3D — đi lại chuyến đi bằng ảnh",
    heroD1: "Đọc giờ và GPS từ ảnh rồi vẽ lộ trình lên quả cầu 3D theo thời gian.",
    heroD2: "Ảnh không GPS ở yên một chỗ — chỉ cần chọn thư mục.",
    heroD3: "Ảnh chỉ đọc trong trình duyệt, không tải lên đâu.",
    gpsOverwrite: "{n} ảnh đã có GPS. Ghi đè thật không?",
    exifrFail: "Thiếu exifr (mạng?)", noPhotos: "Không ảnh/video", wPiexif: "Thiếu piexif", wVerify: "xác minh lỗi",
  },
  id: {
    home: "⌂ Beranda", homeTitle: "Daftar perjalanan",
    mapStreet: "🗺 Peta", mapSat: "🛰 Satelit", mapTerrain: "⛰ Medan", mapBld: "🏢 3D",
    tripsTitle: "Pilih perjalanan", localOpen: "📂 Buka folder",
    noTrips: "📂 Pilih folder travel lokal (foto hanya dibaca di browser, tidak diunggah)",
    play: "▶ Putar", pause: "⏸ Jeda", first: "⏮ Awal", firstTitle: "Ke foto pertama",
    normal: "1x", manualBtn: "📍 Tandai tempat", manualBtnTitle: "Tandai manual ruas tanpa GPS",
    heldChk: "Tampil estimasi", follow: "Ikuti",
    manualTitle: "📍 Tandai tempat manual", mqPh: "cth. Bandara Cheongju", search: "Cari",
    searching: "Mencari...", noResult: "Nihil", searchFail: "Cari gagal (jaringan): ",
    placeFallback: "Tempat tertanda",
    scopeCurrent: "Foto ini saja", scopeBefore: "Foto sebelum GPS pertama", scopeRange: "Rentang waktu",
    photoUnit: " foto",
    mnote: "Tempat jadi jangkar baru dan menata foto · Juga tulis ke EXIF JPEG (folder dapat ditulis)",
    apply: "OK", rulesTitle: "Tersimpan", export: "Ekspor", import: "Impor",
    del: "Hapus", none: "Nihil", notArray: "Bukan array",
    scopeBeforeList: "Semua sebelum GPS pertama", photoOne: "Foto: ",
    badgeGps: "GPS", badgeHeld: "Tertanda", badgeManual: "Manual",
    segStay: "🚶 Berhenti", segWalk: "🚶 Jalan/berhenti", segTransit: "🚇 Kendaraan", segPlane: "✈️ Terbang", segShip: "🚢 Kapal",
    segManualFallback: "Manual",
    day: "Hari {n}", airport: "Bandara", stay: "Inap",
    interlude: "Hari {n}: bangun + kemas",
    stats: "Total {total} · GPS {gps} · Tertanda {held} · Manual {manual} · {start} ~ {end}",
    infoTime: "Waktu", infoMove: "Ruas", infoAt: "Di", infoFile: "File",
    heic: "Pratinjau HEIC tidak bisa", heicDl: "Unduh asli",
    mapIs: "Peta: {x}", mapFailOver: "Peta gagal → {x}", mapFailAll: "Peta gagal dimuat (jaringan?)",
    mapTileErr: "Tile error — cek jaringan", styleFail: "Style gagal — muat ulang",
    initFail: "Init gagal: ",
    openFailRo: "Buka gagal, baca saja: ", reading: "Baca {a}/{b}...", readFail: "Baca gagal: ",
    gpsNoNeed: "Foto GPS tak perlu tanda", needRange: "Isi rentang waktu",
    importFail: "Impor gagal: ",
    wNoPiexif: "Tulis gagal: piexif hilang",
    wNoPerm: "Tulis gagal: tanpa izin (buka folder lagi) · {n} layar saja",
    wNoJpeg: "Asli: lewati {n} non-JPEG, layar saja",
    wProg: "Menulis asli {a}/{b}...",
    wDone: "Asli selesai: {ok} ok{fail} · jangkar GPS",
    wDoneFail: ", {n} gagal", wDoneSkip: ", {n} lewat",
    minTitle: "Ciutkan/buka", localTag: "(lokal)", emptyTrip: "Belum ada foto (perlu waktu)", compassTitle: "Utara", moverBtn: "🚶 Ikon",
    heroTitle: "Peta perjalanan 3D — jalan lagi dengan foto",
    heroD1: "Baca waktu dan GPS foto lalu gambar rute di globe 3D urut waktu.",
    heroD2: "Foto tanpa GPS tetap di tempat — cukup pilih folder.",
    heroD3: "Foto hanya dibaca di browser, tak diunggah.",
    gpsOverwrite: "{n} foto sudah ada GPS. Timpa betulan?",
    exifrFail: "exifr hilang (jaringan?)", noPhotos: "Tanpa foto/video", wPiexif: "piexif hilang", wVerify: "verifikasi gagal",
  },
};
let LANG = null;
try { LANG = localStorage.getItem("tm_lang") || null; } catch (e) {}
if (!STR[LANG]) LANG = null;
function T(key, params) {
  let s = (LANG && STR[LANG] && STR[LANG][key]) ?? STR.ko[key] ?? key;
  if (params) for (const k in params) s = s.replace("{" + k + "}", params[k]);
  return s;
}
function setLang(l) {
  if (!STR[l]) return;
  LANG = l;
  try { localStorage.setItem("tm_lang", l); } catch (e) {}
  document.documentElement.lang = l === "zh" ? "zh-CN" : l === "ja" ? "ja" : l;
  document.querySelectorAll("[data-i18n]").forEach(el => { el.textContent = T(el.dataset.i18n); });
  document.querySelectorAll("[data-i18n-ph]").forEach(el => { el.placeholder = T(el.dataset.i18nPh); });
  document.querySelectorAll("[data-i18n-title]").forEach(el => { el.title = T(el.dataset.i18nTitle); });
  const sel = document.getElementById("langSel");
  if (sel) sel.value = l;
  shownDay = null;
  if (typeof TL !== "undefined" && TL) {
    if (typeof renderRules === "function") renderRules();
    if (typeof renderAll === "function") renderAll(idx);
    $("mapstatus").textContent = T("mapIs", { x: mapLabel(baseKind) });
  } else if (typeof showHome === "function") {
    showHome();
  }
}
